#Creating data frame
library(readr)
chocolate <- read_csv("data/chocolate.csv")
View(chocolate)
chocolate <- data.frame(chocolate)

#--------------------------------------------------
#SUMMARY STATISTICS

#Finding class of each column
library(tibble)
column_names = colnames(chocolate)
column_types = sapply(chocolate, class)
column_statistics = as_tibble(data.frame(column_names, column_types))
View(column_statistics)

summary(chocolate)

#Finding summary statistics for numeric columns
library(dplyr)
summary(select(chocolate, c(review_date, cocoa_percent, rating, counts_of_ingredients)))


#Finding distinct values for non numeric columns
Distinct_Columns <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(Distinct_Columns) = c("Column", "No. of distinct entries")

index <- 1;
for (number in 1:19){
  column <- column_statistics$column_names[number]
  type <- column_statistics$column_types[number]
  if (type == 'character'){
    unique_values <- unique(na.omit(chocolate[column])) #unique values after omitting NA
    distinct_count <- nrow(unique_values)
    
    #Adding, column and distinct count to a separate dataframe
    Distinct_Columns[index,] <- list(column, distinct_count)
    index <- index + 1;
    
    #Displaying first 5 unique values of category
    first_5 <- head(unique_values, n = 5)
    print(first_5[1])
  }
}


#-------------------------------------------------

#PLOTTING
library(ggplot2)

#Selecting top 10 companies
freq_Origin = as.data.frame(table(chocolate$company))
colnames(freq_Origin) = c("Company", "Frequency")

# The top 10 chocolate bar producers
top10s = dplyr::arrange(freq_Origin, desc(Frequency))[1:10,]
onlytops = dplyr::filter(chocolate, company %in% top10s[,1]) 

#First plot
#1. Bar plot of the top 10 producers considering the number of ingredients used
ggplot(onlytops, aes(x = company, fill = factor(counts_of_ingredients))) + geom_bar() +
  theme_bw() + scale_fill_manual(values = c("2" = "#880E4F", "3" = "#FFF176","4" = "#64B5F6", "5" = "#7E57C2"))

#Second plot
#2. Scatter plot of changes in the ratings of chocolate bars (2006-2020)
ggplot(onlytops, aes(x = review_date, y = rating, color = company)) + 
  geom_point()  + facet_wrap(~ company, nrow = 2) + geom_line() + theme_bw() +
  scale_x_continuous(breaks = seq(2005,2021,2), guide = guide_axis(angle = 90))

# aes() function is often used within other graphing elements to specify the desired aesthetics.
# the function geom_point() adds a layer of points, which creates a scatterplot.
# facet_wrap() makes a long ribbon of panels (generated by any number of variables) and wraps it into 2d
# nrow control how many columns
# scale_x_continuous is a scale breaks: manually label the ticks
# guide = rotate the year labels

#Third plot
#3. Violin plot of the distribution of ratings
ggplot(onlytops, aes(x = company, y = rating)) + geom_violin() +
  geom_boxplot(width=0.1, fill="white") +theme_bw()


# How many chocolates contain a particular ingredient?
total_chocolates = nrow(chocolate)
print(total_chocolates)

ingredients = colnames(chocolate[10:16])
for (ingredient in ingredients) {
  chocolates_having_ingredient = sum(chocolate[ingredient] == 1)
  percent_chocolates = as.character(formatC((chocolates_having_ingredient/total_chocolates) * 100, digits=2, format="f"))
  cat(sprintf("%s percent of chocolates have %s in them\n", percent_chocolates, ingredient))
}
